### ISSUE TITLE
refactor: 마이페이지에서 기술 제공 기록 표 수정

### ISSUE THREAD

**Issue by anchangmin35** [Engineering-Student-An/Elice_3rd_project_MOSOO-frontend#63]
In GitLab by @anchangmin on Dec 11, 2024, 21:07

## 어떤 기능인가요?

> 기술 제공 기록 표에서 #이 아닌 다른 글자로 수정

## 작업 상세 내용

- [x] 표 헤더의 글자 수정

## 참고할만한 자료(선택)

**Comment by Engineering-Student-An** [comment]
In GitLab by @anchangmin on Dec 11, 2024, 21:08

mentioned in commit c04d42c3a923be9e3d048ae8a15a78d1b5b89317

**Comment by Engineering-Student-An** [comment]
In GitLab by @anchangmin on Dec 11, 2024, 21:08

marked the task **표 헤더의 글자 수정** as completed

**Comment by Engineering-Student-An** [comment]
In GitLab by @anchangmin on Dec 11, 2024, 21:09

mentioned in commit 884e95f684820d0cc6518159b473c82cdc232115
